### ISSUE TITLE
Loosen Pillow dependency

### ISSUE THREAD

**Issue by barseghyanartur** [dfface/xml2epub#37]
ATM, it's hard pinned to 9.5.0. Is there any reason for that?

**Comment by dfface** [comment]
> ATM, it's hard pinned to 9.5.0. Is there any reason for that?

Here is.

https://github.com/dfface/xml2epub/issues/28

**Comment by dfface** [comment]
v2.6.6 solve this.

**Comment by barseghyanartur** [comment]
> v2.6.6 solve this.

Thanks!
